"use client";

import { useEffect, useState } from "react";
import { BookOpen, BriefcaseBusiness, CheckCircle2, ChevronRight, Clock3, Code2, GraduationCap, Laptop2, MapPin, Menu, MessageCircle, Phone, Quote, Star, Users, X } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const courses = [
  { icon: Code2, tag: "Most Popular", title: "Full Stack Development", text: "HTML, CSS, JavaScript, React, Node.js & live projects", duration: "6 Months", level: "Beginner to Pro" },
  { icon: Laptop2, tag: "Career Course", title: "Python Programming", text: "Python fundamentals, automation, databases & projects", duration: "4 Months", level: "Beginner Friendly" },
  { icon: BriefcaseBusiness, tag: "Job Ready", title: "Tally Prime + GST", text: "Accounting, inventory, taxation, payroll & GST filing", duration: "3 Months", level: "Practical Training" },
  { icon: BookOpen, tag: "Essential", title: "MS-CIT & Office", text: "Computer basics, Word, Excel, PowerPoint & internet skills", duration: "3 Months", level: "All Learners" },
  { icon: GraduationCap, tag: "Creative", title: "Graphic Designing", text: "Photoshop, CorelDRAW, Canva and brand design", duration: "4 Months", level: "Portfolio Based" },
  { icon: Users, tag: "Fast Track", title: "Advanced Excel", text: "Formulas, dashboards, PivotTables and reporting", duration: "2 Months", level: "Office Skills" },
];

const batches = [
  ["Morning", "07:30 AM – 09:00 AM", "Mon – Sat", "12 seats"], ["College Batch", "11:00 AM – 12:30 PM", "Mon – Sat", "8 seats"],
  ["Evening", "04:00 PM – 05:30 PM", "Mon – Sat", "15 seats"], ["Weekend", "10:00 AM – 01:00 PM", "Sat – Sun", "10 seats"],
];

type FormMode = "admission" | "enquiry";

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [mode, setMode] = useState<FormMode>("admission");
  const [open, setOpen] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  useEffect(() => { const reveal = () => document.querySelectorAll(".reveal").forEach((el) => { if (el.getBoundingClientRect().top < innerHeight - 70) el.classList.add("visible"); }); reveal(); addEventListener("scroll", reveal); return () => removeEventListener("scroll", reveal); }, []);
  const launchForm = (next: FormMode) => { setMode(next); setSubmitted(false); setOpen(true); };
  const submit = (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); const leads = JSON.parse(localStorage.getItem("disha-enquiries") || "[]"); localStorage.setItem("disha-enquiries", JSON.stringify([{ ...data, type: mode, createdAt: new Date().toISOString() }, ...leads])); setSubmitted(true); };

  return <main>
    <header className="topbar"><div className="container nav-wrap"><a href="#home" className="brand"><span className="brand-mark">D</span><span><b>DISHA</b><small>Computer Institute</small></span></a><nav className={menuOpen ? "nav-links open" : "nav-links"}>{[["Home","home"],["Courses","courses"],["Batches","batches"],["Placements","placements"],["Contact","contact"]].map(([label,id]) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)}>{label}</a>)}<button className="btn btn-small" onClick={() => launchForm("admission")}>Apply Now <ChevronRight size={16}/></button></nav><button className="menu-btn" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X/> : <Menu/>}</button></div></header>
    <section className="hero" id="home"><div className="hero-grid-bg"/><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span/> Admissions Open 2026</div><h1>Skills that shape<br/><em>your future.</em></h1><p>Practical computer education, expert trainers and career-focused courses—right here in Yavatmal.</p><div className="hero-actions"><button className="btn" onClick={() => launchForm("admission")}>Explore Admissions <ChevronRight size={18}/></button><button className="btn btn-ghost" onClick={() => launchForm("enquiry")}><Phone size={17}/> Request a Call</button></div><div className="trust-row"><div className="avatars"><i>A</i><i>S</i><i>R</i><i>+</i></div><div><span className="stars">★★★★★</span><b> 4.9</b><small>Loved by 819+ students</small></div></div></div><div className="hero-visual"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="screen-card"><div className="screen-top"><span/><span/><span/></div><div className="code-line w80"/><div className="code-line w55"/><div className="code-line yellow w70"/><div className="code-line w45"/><div className="screen-chart"><i/><i/><i/><i/><i/></div></div><div className="float-card card-students"><Users size={20}/><span><b>5,000+</b><small>Students trained</small></span></div><div className="float-card card-placement"><CheckCircle2 size={20}/><span><b>Career ready</b><small>Practical learning</small></span></div></div></div></section>
    <section className="quick-strip"><div className="container quick-grid">{[[GraduationCap,"Industry Courses","Modern, job-ready syllabus"],[Users,"Expert Trainers","Personal guidance"],[BriefcaseBusiness,"Placement Support","Resume & interview prep"],[Clock3,"Flexible Batches","Morning to weekend"]].map(([Icon,title,text]: any) => <div key={title}><Icon/><span><b>{title}</b><small>{text}</small></span></div>)}</div></section>
    <section className="section" id="courses"><div className="container"><div className="section-head reveal"><div><span className="kicker">OUR COURSES</span><h2>Learn today. Lead tomorrow.</h2></div><p>Choose a practical course designed around current industry needs and real-world skills.</p></div><div className="course-grid">{courses.map((c,i) => <article className="course-card reveal" key={c.title} style={{transitionDelay:`${i*60}ms`}}><div className="course-icon"><c.icon/></div><span className="tag">{c.tag}</span><h3>{c.title}</h3><p>{c.text}</p><div className="course-meta"><span><Clock3/> {c.duration}</span><span><GraduationCap/> {c.level}</span></div><button onClick={() => launchForm("admission")}>View course <ChevronRight size={16}/></button></article>)}</div></div></section>
    <section className="section batch-section" id="batches"><div className="container batch-layout"><div className="reveal"><span className="kicker light">FLEXIBLE LEARNING</span><h2>Find a batch that fits your day.</h2><p>Morning, evening and weekend options let you learn without putting college or work on hold.</p><ul><li><CheckCircle2/> Small batch sizes</li><li><CheckCircle2/> Hands-on lab practice</li><li><CheckCircle2/> Backup sessions available</li></ul></div><div className="batch-card reveal"><Tabs defaultValue="weekday"><TabsList className="batch-tabs"><TabsTrigger value="weekday">Weekday</TabsTrigger><TabsTrigger value="weekend">Weekend</TabsTrigger></TabsList><TabsContent value="weekday">{batches.slice(0,3).map(b => <BatchRow b={b} key={b[0]}/>)}</TabsContent><TabsContent value="weekend"><BatchRow b={batches[3]}/></TabsContent><button className="btn full" onClick={() => launchForm("admission")}>Reserve Your Seat</button></Tabs></div></div></section>
    <section className="section" id="placements"><div className="container"><div className="results-grid reveal"><div><span className="kicker">PLACEMENT & RESULTS</span><h2>More than a certificate.<br/>A confident career start.</h2><p>Our students build portfolios, practise interviews and receive dedicated career guidance.</p><button className="text-btn" onClick={() => launchForm("enquiry")}>Talk to a career counsellor <ChevronRight/></button></div><div className="stat-grid"><div><b>5,000<sup>+</sup></b><span>Students trained</span></div><div><b>92<sup>%</sup></b><span>Course completion</span></div><div><b>50<sup>+</sup></b><span>Hiring connections</span></div><div><b>12<sup>+</sup></b><span>Years of learning</span></div></div></div><div className="testimonial reveal"><Quote/><p>“The practical sessions and personal guidance helped me gain confidence and become job-ready. Disha gave my career the right direction.”</p><div><b>Student Success Story</b><span><Star fill="currentColor"/> 4.9 rated institute</span></div></div></div></section>
    <section className="cta-section"><div className="container cta-box reveal"><div><span className="kicker light">START YOUR JOURNEY</span><h2>Your next skill starts here.</h2><p>Speak with our counsellor and choose the right course and batch.</p></div><div className="cta-actions"><button className="btn btn-light" onClick={() => launchForm("admission")}>Register Online</button><a href="tel:+917020450251" className="phone-link"><Phone/><span><small>Call us now</small><b>+91 70204 50251</b></span></a></div></div></section>
    <footer id="contact"><div className="container footer-grid"><div><a href="#home" className="brand footer-brand"><span className="brand-mark">D</span><span><b>DISHA</b><small>Computer Institute</small></span></a><p>Practical computer education for a brighter, skilled future.</p></div><div><h4>Visit Us</h4><p><MapPin/> Godhani Road, Yavatmal, Maharashtra</p></div><div><h4>Connect</h4><a href="tel:+917020450251"><Phone/> +91 70204 50251</a><button onClick={() => launchForm("enquiry")}><MessageCircle/> Send an enquiry</button></div></div><div className="container footer-bottom"><span>© 2026 Disha Computer Institute, Yavatmal</span><span>Learning • Skills • Success</span></div></footer>
    <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><span/></DialogTrigger><DialogContent className="form-dialog"><DialogHeader><DialogTitle>{submitted ? "Thank you!" : mode === "admission" ? "Online Registration" : "Course Enquiry"}</DialogTitle><DialogDescription>{submitted ? "Your details have been received. Our counsellor will contact you shortly." : "Share your details and our Yavatmal team will guide you."}</DialogDescription></DialogHeader>{submitted ? <div className="success-state"><CheckCircle2/><b>Request submitted successfully</b><button className="btn" onClick={() => setOpen(false)}>Done</button></div> : <form onSubmit={submit} className="lead-form"><label>Full name<input name="name" required placeholder="Enter your name"/></label><label>Mobile number<input name="phone" required inputMode="tel" pattern="[0-9]{10}" placeholder="10-digit mobile number"/></label><label>Email address<input name="email" type="email" placeholder="you@example.com"/></label><label>Interested course<select name="course" required defaultValue=""><option value="" disabled>Select a course</option>{courses.map(c => <option key={c.title}>{c.title}</option>)}</select></label><label>Preferred batch<select name="batch" defaultValue="Morning"><option>Morning</option><option>College Batch</option><option>Evening</option><option>Weekend</option></select></label><button className="btn full" type="submit">Submit {mode === "admission" ? "Registration" : "Enquiry"}</button><small>By submitting, you agree to be contacted about course information.</small></form>}</DialogContent></Dialog><a className="whatsapp" href="https://wa.me/917020450251" target="_blank" rel="noreferrer" aria-label="Chat on WhatsApp"><MessageCircle/></a>
  </main>;
}

function BatchRow({b}:{b:string[]}) { return <div className="batch-row"><div><b>{b[0]}</b><small>{b[2]}</small></div><strong>{b[1]}</strong><span>{b[3]}</span></div>; }
